# Pizza API

## To use these HTTP endpoints, install the REST Client plugin in VSCode.

### Get all the Pizzas from the API
GET https://pizza-api.projectcodex.net/api/pizzas

### Create a cart
GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Loyiso-Xaba

### Get a cart
GET https://pizza-api.projectcodex.net/api/pizza-cart/V1ImICVlUf/get

### Add a pizza to the cart
POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "V1ImICVlUf",
    "pizza_id": 9
}

### Remove a pizza from the cart
POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
Content-Type: application/json

{
    "cart_code": "V1ImICVlUf",
    "pizza_id": 10
}

### GET all the carts for a given user
GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Loyiso-Xaba

### GET all the active carts for a user
GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Loyiso-Xaba/active

### Pay for a pizza from the cart
POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
Content-Type: application/json

{
    "cart_code": "irfiTfdh8h",
    "amount": 50.00
}
